### PR TITLE
WIP - init viadict

### PR DESCRIPTION
**Pull request by mhammond**
This "works" insofar as we make a request to the stage server.

### CODE REVIEW

**Comment by rfk** [comment]
I had a brief poke at this, but it seems to fail for me in the same way it fails for you (which is good I guess!). FWIW I wouldn't be opposed to dragging along the protobuf plugin if it helps us get to something that works short-term.

**Comment by travis79** [comment]
I'll check this out and give it a go today 🤞

**Comment by travis79** [comment]
Here's my go at getting this working for you, hope it helps: https://github.com/mhammond/nimbus-sdk/pull/1

**Comment by mhammond** [comment]
Abandoning this for now in favor of the nimbus-megazord branch.

**Pull request closed without merging**
