### PR TITLE
Update uniffi in order to set package name

### PR DESCRIPTION
**Pull request by travis79**
Add uniffi.toml with package name

### CODE REVIEW

**Comment by travis79** [comment]
Putting this up as a Draft PR until [the bug in uniffi to find the cargo manifest](https://github.com/mozilla/uniffi-rs/issues/304) is fixed

**Comment by travis79** [comment]
Seems to work all the way through to my WIP Android component, via MavenLocal! Since this is a bit of a breaking change, I went ahead and incremented the version number.  Since we haven't actually _released_ anything yet, I think we can forget the changelog for now but I'll file an issue to add one.

**Review by mhammond — APPROVED** [review]
rubber-stamp - I'll update the megazord branch after this lands.

**Comment by travis79** [comment]
I just rebased and force-pushed, I'm going to wait a bit for Circle to see if it runs or not.

**Comment by travis79** [comment]
Nope, Circle didn't love me today :(

**Comment by travis79** [comment]
Since I don't even see this as a job in Circle for this project, I guess I'll go ahead and merge this as I don't know how to kick a job that isn't there :/

**Pull request merged**
