### PR TITLE
Bump uniffi dependency to 0.4.0 to fix license goofiness for m-c

### PR DESCRIPTION
**Pull request by dmose**
Obviously, CI won't pass and I won't try to land this until after the uniffi PR lands.

### CODE REVIEW

**Review by rfk — APPROVED** [review]
uniffi v0.4.0 is out, and this LGTM 👍

**Comment by dmose** [comment]
I saw exactly the same error locally.  It turned that I had `uniffi_bindgen 0.3.0` installed in `~/.cargo/bin`.  What I had to do to fix it was do `cargo uninstall uniffi_bindgen && cargo install uniffi_bindgen`.  @rfk, does mean that we will need to update the docker image shortly before or after we land this PR?

```
   Compiling nimbus-sdk v1.0.0 (/root/project/nimbus)
error: failed to run custom build command for `nimbus-sdk v1.0.0 (/root/project/nimbus)`

Caused by:
  process didn't exit successfully: `/root/project/nimbus/target/debug/build/nimbus-sdk-2e4b887a0f7f59eb/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=./src/nimbus.idl

  --- stderr
  Error: The `uniffi` dependency version (0.4.0) is different than `uniffi-bindgen` own version (0.3.0). Please rectify the problem and try again.
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error while generating scaffolding code', build.rs:6:60
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by rfk** [comment]
@dmose aha, looks like `.circleci/config.yml` is hard-coding a specific version of uniffi to install for the tests, we should either update it there as well, or figure out how to have that install the version specified in `Cargo.tom`.

**Comment by mhammond** [comment]
> @dmose aha, looks like `.circleci/config.yml` is hard-coding a specific version of uniffi to install for the test

The megazord branch has a similar issue - [here's one place](https://github.com/mozilla/application-services/blob/nimbus-megazord/megazords/full/android/build.gradle#L67) and I think there are others.

Ironically, uniffi-build says:

    // Calling the command line helps making sure that the generated swift/Kotlin/whatever
    // bindings were generated with the same version of uniffi as the Rust scaffolding code.

but as we see, that doesn't seem quite true. Is this still the right tradeoff? Regardless, this seems likely to bite us more and more

**Comment by dmose** [comment]
So it sounds like the proposal is to switch to _always_ using
builtin_bindgen, which seems reasonable to me.  I'd love to hear @eoger's
thoughts on this...

**Comment by eoger** [comment]
I'm against using `builtin_bindgen`, because it can introduce subtle breakage between Kotlin and Rust layers, but I won't block it.

**Comment by dmose** [comment]
@eoger Can you unpack that subtle breakage a bit more?  Both so that we as developers could recognize it in the future, but also to see if we can brainstorm a fix that doesn't have that issue, while also not having the fragility of the current setup?

I mean, I could image a world where the right thing to do is simpy have a build_dependency on `uniffi_bindgen` instead of on `uniffi_build`, and clients would be expect to write their own logic to generate artifacts from udl files.  Does that sounds like a better option?

**Comment by dmose** [comment]
Couldn't one even make the argument that uniffi_bindgen should be available as a feature of uniffi itself,  I can't imagine ever wanting to use different versions of those things?

**Comment by rfk** [comment]
It's also worth noting that we have some additional layers of protection against dylib/bindings incompatibility now, such as https://github.com/mozilla/uniffi-rs/issues/333 (which includes the uniffi version as part of the fingerprint to include in the symbol names).

**Comment by dmose** [comment]
As discussed in today's meeting, not blocking on finding the ideal solution.  Fixes JIRA:SDK-93

**Pull request merged**
